config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'application#home'

  resources :categories
  resources :earnings
  resources :expenses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# Manage expense categorization.
class Category < ApplicationRecord
  validates :name, presence: true

  belongs_to :user

  has_many :subcategories, class_name: 'Category',
                           foreign_key: 'parent_category_id'
  belongs_to :parent_category, class_name: 'Category', optional: true

  has_many :expenses

  def description
    name
  end
end

app/models/earning.rb
class Earning < ApplicationRecord
  monetize :amount_cents

  validates :name, presence: true
  validates :date, presence: true
  validates :amount_cents, presence: true, numericality: { greater_than: 0 }

  def description
    "#{name} (#{amount})"
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
  monetize :price_cents

  belongs_to :category

  validates :name, presence: true
  validates :date, presence: true
  validates :price_cents, presence: true, numericality: { greater_than: 0 }

  def description
    "#{name} (#{price})"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def home
    redirect_to expenses_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  before_action :load_categories, only: [:index, :new]
  before_action :load_current_category,
                only: [:show, :category, :destroy, :edit]

  def new
    @category = Category.new
    @available_categories = @categories
  end

  def create
    @category = Category.new(category_params.merge(user: current_user))
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @available_categories = @categories.where.not(id: params[:id])
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :parent_category_id)
  end

  def record_not_found
    # TODO: Add flash error message
    redirect_to action: 'index'
  end

  def load_categories
    @categories ||= current_user.categories
  end

  def load_current_category
    load_categories
    @category ||= @categories.find(params[:id])
  end
end

app/controllers/earnings_controller.rb
class EarningsController < ApplicationController
  def index
    @earnings = Earning.all
  end

  def new
    @earning = Earning.new
  end

  def create
    @earning = Earning.new(earning_params)
    @earning.date = Time.zone.now
    if @earning.save
      redirect_to @earning
    else
      render 'new'
    end
  end

  def show
    @earning = Earning.find(params[:id])
  end

  def edit
    @earning = Earning.find(params[:id])
  end

  def update
    @earning = Earning.find(params[:id])
    if @earning.update_attributes(earning_params)
      redirect_to earnings_path
    else
      render 'edit'
    end
  end

  def destroy
    Earning.find(params[:id]).destroy
    redirect_to earnings_path
  end

  private

  def earning_params
    params.require(:earning).permit(:name, :amount_cents)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @expenses = Expense.all
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.date = Time.zone.now
    if @expense.save
      redirect_to @expense
    else
      render 'new'
    end
  end

  def show
    @expense = Expense.find(params[:id])
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def update
    @expense = Expense.find(params[:id])
    if @expense.update_attributes(expense_params)
      redirect_to expenses_path
    else
      render 'edit'
    end
  end

  def destroy
    Expense.find(params[:id]).destroy
    redirect_to expenses_path
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :price_cents, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/earnings_helper.rb
module EarningsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/categories/edit.html.erb
<%= simple_form_for @category do |f| %>
    <%= f.input :name %>
    <%= f.association :parent_category, collection: @available_categories,
                                            prompt: 'Choose category' %>
    <%= f.button :submit %>
<% end %>

<%=  link_to 'Cancel', categories_path %>

app/views/categories/index.html.erb
<%= render layout: 'shared/index_layout', locals: { type: :category } do %>
    <%= render 'shared/list_entities', entities: @categories %>
<% end %>

app/views/categories/new.html.erb
<%= simple_form_for @category do |f| %>
    <%= f.input :name %>
    <%= f.association :parent_category, collection: @available_categories,
                                            prompt: 'Choose category' %>
    <%= f.button :submit %>
<% end %>

<%=  link_to 'Cancel', categories_path %>

app/views/categories/show.html.erb
<%= render layout: 'shared/show_layout', locals: { entity: @category } do %>
    <%= render 'shared/list_entities', type: :expense, entities: @category.expenses %>
<% end %>

app/views/earnings/edit.html.erb
<%= simple_form_for @earning do |f| %>
    <%= f.input :amount_cents %>
    <%= f.input :name %>
    <%= f.button :submit %>
<% end %>

<%=  link_to 'Cancel', earnings_path %>

app/views/earnings/index.html.erb
<%= render layout: 'shared/index_layout', locals: { type: :earning } do %>
    <%= render 'shared/list_entities', entities: @earnings %>
<% end %>

app/views/earnings/new.html.erb
<%= simple_form_for @earning do |f| %>
    <%= f.input :amount_cents %>
    <%= f.input :name %>
    <%= f.button :submit %>
<% end %>

<%=  link_to 'Cancel', earnings_path %>

app/views/earnings/show.html.erb
<%= render layout: 'shared/show_layout', locals: {entity: @earning} do %>
<p>
    Amount: <%= @earning.amount %><br>
    Date: <%= @earning.date %>
</p>
<% end %>

app/views/expenses/edit.html.erb
<%= simple_form_for @expense do |f| %>
    <%= f.input :price_cents %>
    <%= f.input :name %>
    <%= f.association :category %>
    <%= f.button :submit %>
<% end %>

<%=  link_to 'Cancel', expenses_path %>

app/views/expenses/index.html.erb
<%= render layout: 'shared/index_layout', locals: { type: :expense } do %>
    <%= render 'shared/list_entities', entities: @expenses %>
<% end %>

app/views/expenses/new.html.erb
<%= simple_form_for @expense do |f| %>
    <%= f.input :price_cents %>
    <%= f.input :name %>
    <%= f.association :category %>
    <%= f.button :submit %>
<% end %>

<%=  link_to 'Cancel', expenses_path %>

app/views/expenses/show.html.erb
<%= render layout: 'shared/show_layout', locals: {entity: @expense} do %>
    <p>
        Amount: <%= @expense.price %><br>
        Date: <%= @expense.date %><br>
        Category: <%= link_to @expense.category.name, category_path(@expense.category) %>
    </p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button"
                    class="navbar-toggle"
                    data-toggle="collapse"
                    data-target="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "PeFi",
                        root_path,
                        id: "logo",
                        class: "navbar-brand navbar-brand-centered" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><%= link_to "Home",            root_path %></li>
                <% if user_signed_in? %>
                    <li><%= link_to "Stats",       '#' %></li>
                    <li><%= link_to "Leaderboard", '#' %></li>
                <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "About",          '#' %></li>
                <% if user_signed_in? %>
                    <li><%= link_to "My Account", '#' %></li>
                    <li><%= link_to "Sign out",   destroy_user_session_path,
                                                  method: :delete %></li>
                <% else %>
                    <li><%= link_to "Sign in",    new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pefi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/navbar' %>
      <div class="container">
          <div class="row">
              <% if user_signed_in? %>
                  <div class="col-sm-3 affix hidden-xs bordered sidebar"
                       id="sidebar">
                  </div>

                  <div class="col-sm-9 col-sm-offset-3 bordered main">
                      <%= yield %>
                  </div>
              <% else %>
                  <div class="col-sm-4 col-sm-offset-4 bordered login">
                      <%= yield %>
                  </div>
              <% end %>
          </div>
      </div>
  </body>
</html>

app/views/shared/_index_expenses.html.erb
<p>
    <table>
        <% entities.each do |entity| %>
            <tr>
                <td><%= link_to "#{entity.description}", entity %></td>
                <td><%= link_to 'Delete', entity, method: :delete %></td>
            </tr>
        <% end  %>
    </table>
</p>

app/views/shared/_index_layout.html.erb
<h1>Listing <%= type.to_s.pluralize %></h1>

<%= yield %>

<%=  link_to "Add #{type}", [:new, type] %>

app/views/shared/_list_entities.html.erb
<p>
    <table>
        <% entities.each do |entity| %>
            <tr>
                <td><%= link_to "#{entity.description}", entity %></td>
                <td><%= link_to 'Delete', entity, method: :delete %></td>
            </tr>
        <% end  %>
    </table>
</p>

app/views/shared/_show_layout.html.erb
<h3><%= "#{entity.class.to_s}: #{entity.name}" %></h3>

<%= yield %>

<%= link_to 'Edit', [:edit, entity] %>
<%= link_to "All #{entity.class.to_s.pluralize.downcase}",
    [entity.class.to_s.pluralize.downcase] %>